feat: add development workflow and update scripts
NativeScript/push-plugin pull request #199
Opened 2018-02-26 12:18 UTC by lini

Updated to new version of nativescript-hook, which allows plugin to be referenced directly from demo app. No longer needed to pack a .tgz first.

2018-02-26 16:25 UTC, tbozhikov requested changes

2018-02-26 16:25 UTC, tbozhikov commented on DevelopmentWorkflow.md
> +cd nativescript-camera/demo
camera -> push-plugin

2018-02-26 16:25 UTC, tbozhikov commented on DevelopmentWorkflow.md
> +- `clean` - clean the demo and plugin directories and build the plugin.
I would expect the clean command to clean only, and not build. A rebuild command should do clean + build. Maybe we can discuss on that.

2018-02-26 16:25 UTC, tbozhikov commented on src/package.json
> +    "clean": "cd ../demo && rimraf hooks node_modules platforms && cd ../src && rimraf node_modules && npm run build",
I would expect the clean command to clean only, and not build. A rebuild command should do clean + build. Maybe we can discuss on that.

2018-03-02 09:09 UTC, nsplugins approved these changes

2018-03-02 09:10 UTC, merged